language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CKWCegcriwa7YIg9EWl5adqZqA9KtcsJBqTo3KO+o8GFap5zY2OtEqGTbeMRIC3k/if926YVowEGBrL6EWmlW2k5u4pIL3JRyYcrhExoQAK14cipi3gbNDSWBVQKIzsNmWwoFlHCLtvxEczFYMndg2yEhw7tePoUbVGfYepP1cRxZPtbD+2Fw2Pu4ozE8yCQ0ucXsDz+H6tDlNT1HPMgeZdPw8hXNIt+1DhajrboQfofLd0aZUJJKBC/hP78s2cgSp7ttPSDqtPsY5lXSMudgBgsTwbl5f2TAoCONc2Zh48fKqNsIWmvheiQEw+avLFtnOnXBYaJJfm/3e6HNtjAE09HSwlh23H1IkW0TVX9fVWZgCMG3HYMZxRRTKb4+zLmPBlSKbXNsXub8s3kXWJADVuV8BFnmqiAtcNpLEEqT1QoXQqJ4xo6MmOwe8aNIDGjHU1/lL5JJ3sR0m/4mcmJC+fUFE2JH6raT4qRG7SViskicG2wSa1zpp9Y0hrZWj4kKLn6BQB/xDjvGPdgg+dgJQqOeKZS8A3HcPZ67O2GSmjPrJE3qI2uPa5c1OSoKKAyzyku76EQExF3n1DX4M+vGh/Ykpfp3d38ipVZZPHI748WABkwCC7gRDx6RtsC7lPc06CM7CrY/NXbGcusp67/SPTS6hDSkSppR+y4R4excZw=
  app: stark-hollows-87235
  on:
    repo: joshhrycek/Node-Capstone
